eureka:
  instance:
    hostname: localhost
  client:
    transport:
      applicationsResolverUseIp: true
#    useDnsForFetchingServiceUrls: true
#    eurekaServerDNSName: eureka.huodongkr.com
#    eurekaServerPort: 8761
#    region: ydd
#    eureka-server-u-r-l-context: eureka
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/

spring:
  application:
    name: eureka-server

server:
  port: 8762