eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/
    healthcheck:
      enabled : true
spring:
  application:
    name: eureka-provider

server:
  port: 8681
  tomcat:
      accept-count: 1000
      max-threads: 1000
      max-connections: 2000
logging:
  level:
    com:
      netflix:
        discovery: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health,info,env,beans,test
#  health:
#    refresh:
#      enabled: false