eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
zuul:
  routes:
    api:
      path: /**
      serviceId: eureka-provider
  host:
      max-per-route-connections: 1000
      max-total-connections: 1000
#  RibbonRoutingFilter:
#    route:
#      disable: true

spring:
  application:
    name: gateway-zuul
server:
  port: 9000
  tomcat:
    accept-count: 1000
    max-threads: 1000
    max-connections: 2000



