eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: eureka-provider

server:
  port: 8081
  tomcat:
      accept-count: 1000
      max-threads: 1000
      max-connections: 2000
