spring:
  application:
    name : eureka-consumer
#  cloud:
#    refresh:
#      enabled: false

server:
  port: 7001

eureka:
  client:
    service-url :
      defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/
    registry-fetch-interval-seconds: 5
    register-with-eureka: false